[package]
name = "truck-base"
version = "0.1.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"
description = "Basic structs and traits: importing cgmath, curve and surface traits, tolerance, etc..."
license = "Apache License 2.0"
keywords = ["truck", "graphics"]
categories = ["graphics"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.17.0"
serde = { version = "1.0.118", features = ["derive"] }
