[package]
name = "truck-modeling"
version = "0.2.1"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"
description = "integrated modeling algorithms by geometry and topology"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hash = "1.1.0"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.29"
truck-base = { version = "0.1.1", path = "../truck-base" }
truck-geotrait = { version = "0.1.0", path = "../truck-geotrait" }
truck-geometry = { version = "0.1.1", path = "../truck-geometry" }
truck-polymesh = { version = "0.2.1", path = "../truck-polymesh" }
truck-shapeops = { version = "0.1.0", path = "../truck-shapeops" }
truck-topology = { version = "0.2.0", path = "../truck-topology" }

[dev-dependencies]
rand = "0.8.4"
serde_json = "1.0.68"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
getrandom = { version = "0.2.3", features = ["js"] }
