[package]
name = "truck-modeling"
version = "0.1.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
truck-base = { path = "../truck-base" }
truck-geometry = { path = "../truck-geometry" }
truck-topology = { path = "../truck-topology" }

[dev-dependencies]
rand = "*"
winit = "*"
futures = "*"
truck-platform = { path = "../truck-platform" }
truck-rendimpl = { path = "../truck-rendimpl" }
