[package]
name = "truck-topology"
version = "0.1.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.2.0"
truck-base = {path = "../truck-base"}

[dev-dependencies]
truck-geometry = {path = "../truck-geometry"}
truck-io = {path = "../truck-io"}
