[package]
name = "truck-topology"
version = "0.4.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "topological structs: vertex, edge, wire, face, shell, and solid"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
rustc-hash = "1.1.0"
truck-base = { version = "0.3.0", path = "../truck-base" }
truck-geotrait = { version = "0.2.0", path = "../truck-geotrait" }
thiserror = "1.0.31"

[dev-dependencies]
