stages:
    - test
    - pages

cpu-test:
    image: rust:latest
    stage: test
    before_script:
        - cargo install cargo-make
    script:
        - cargo make ci-cpu-test
    cache:
        key: cpu-test
        paths:
          - cargo/
    variables:
        CARGO_HOME: $CI_PROJECT_DIR/cargo

gpu-test:
    image: registry.ritc.jp/ricos/truck/truck/rust-vulkan:_no_branch
    stage: test
    script:
        - /root/.cargo/bin/cargo make ci-gpu-test
    tags:
        - gpu
    artifacts:
        paths:
            - images

wasm-test:
    image: registry.ritc.jp/ricos/truck/truck/rust-webtools:_no_branch
    stage: test
    before_script:
        - rustup target add wasm32-unknown-unknown
    script:
        - mkdir public
        - cargo make wasm-test
        - mv truck-js/pkg public/adhoc-viewer
        - mv dist public/webgpu-examples
    artifacts:
        paths:
            - public

pages:
    image: rust:latest
    stage: pages
    script:
        - cargo doc --no-deps
        - mv target/doc public/doc
    artifacts:
        paths:
            - public
    only:
        - master
