stages:
    - test
    - pages

test:
    image: rust:latest
    stage: test
    before_script:
        - apt-get update -y
        - apt-get install cmake -y
    script:
        - cargo test
    except:
        - master
    tags:
        - gpu

pages:
    image: registry.ritc.jp/ricos/truck/truck/rust-vulkan:_no_branch
    stage: pages
    script:
        - /root/.cargo/bin/cargo clean
        - /root/.cargo/bin/cargo test
        - /root/.cargo/bin/cargo doc --no-deps
        - cp -r target/doc public
    artifacts:
        paths:
            - public
    tags:
        - gpu
    only:
        - master