stages:
    - test
    - pages

test:
    image: rust:latest
    stage: test
    cache:
        paths:
            - target
    script:
        - cargo test
    except:
        - master

pages:
    image: rust:latest
    stage: pages
    script:
        - cargo clean
        - cargo test
        - cargo doc --no-deps
        - cp -r target/doc public
    artifacts:
        paths:
            - public
    only:
        - master