stages:
    - test
    - pages

cpu-test:
    image: rust:latest
    stage: test
    cache:
        paths:
            - /usr/local/cargo/bin/cargo-make
    before_script:
        - cargo install cargo-make
    script:
        - cargo make ci-cpu-test

gpu-test:
    image: registry.ritc.jp/ricos/truck/truck/rust-vulkan:_no_branch
    stage: test
    script:
        - /root/.cargo/bin/cargo make ci-gpu-test
    tags:
        - gpu
    artifacts:
        paths:
            - images


wasm-build:
    image: rust:latest
    stage: test
    cache:
        paths:
            - /usr/local/cargo/bin/cargo-make
    before_script:
        - cargo install cargo-make
        - rustup target add wasm32-unknown-unknown
    script:
        - cargo make wasm-build

    
pages:
    image: rust:latest
    stage: pages
    script:
        - cargo doc --no-deps
        - mv target/doc public
    artifacts:
        paths:
            - public
    only:
        - master
