stages:
    - test
    - deploy

test:
    image: rust:latest
    stage: test
    cache:
        paths:
            - target
    script:
        - cargo test
    except:
        - master

pages:
    image: rust:latest
    stage: deploy
    script:
        - cargo clean
        - cargo test
        - cargo doc --no-deps
    artifacts:
        paths:
            - target/doc
    only:
        - master