stages:
    - test
    - pages

cpu-test:
    image: rust:latest
    stage: test
    script:
        - cargo clean
        - cargo test -p truck-base
            -p truck-geotrait
            -p truck-geometry
            -p truck-topology
            -p truck-polymesh
            -p truck-modeling
            -- --nocapture

gpu-test:
    image: registry.ritc.jp/ricos/truck/truck/rust-vulkan:_no_branch
    stage: test
    script:
        - /root/.cargo/bin/cargo clean
        # test by release build for the bug of Vulkan-ValidationLayers
        # cf: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2502
        - /root/.cargo/bin/cargo test --release
            -p truck-platform
            -p truck-rendimpl
            -- --nocapture --test-threads=1
        - mkdir images
        - mv truck-platform/output images/platform
        - mv truck-rendimpl/output images/rendimpl
    tags:
        - gpu
    artifacts:
        paths:
            - images

pages:
    image: rust:latest
    stage: pages
    script:
        - cargo doc --no-deps
        - mv target/doc public
    artifacts:
        paths:
            - public
    only:
        - master
