stages:
    - test
    - pages

cpu-test:
    image: rust:latest
    stage: test
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
        CARGO_HOME: $CI_PROJECT_DIR/cargo
    before_script:
        - cargo install cargo-make
    script:
        - cargo make ci-cpu-test
    cache:
        key: cpu-test
        paths:
          - cargo/

gpu-test:
    image: registry.ritc.jp/ricos/truck/truck/rust-vulkan:_no_branch
    stage: test
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    before_script:
        - apt-get install -y cmake
    script:
        - /root/.cargo/bin/rustup toolchain uninstall stable
        - /root/.cargo/bin/rustup toolchain install stable
        - /root/.cargo/bin/cargo make ci-gpu-test
    tags:
        - gpu
    artifacts:
        paths:
            - images

wasm-test:
    image: registry.ritc.jp/ricos/truck/truck/rust-webtools:_no_branch
    stage: test
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    before_script:
        - rustup toolchain uninstall stable
        - rustup toolchain install stable
        - rustup target add wasm32-unknown-unknown
        - cargo install -f wasm-bindgen-cli
    script:
        - deno lint
        - cargo make wasm-test

page-build:
    image: registry.ritc.jp/ricos/truck/truck/rust-webtools:_no_branch
    stage: test
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    before_script:
        - rustup toolchain uninstall stable
        - rustup toolchain install stable
        - rustup target add wasm32-unknown-unknown
        - cargo install -f wasm-bindgen-cli
    script:
        - mkdir public
        - cargo make page-build
        - mv truck-js/pkg public/adhoc-viewer
        - mv dist public/webgpu-examples
    artifacts:
        paths:
            - public

lint-check:
    image: rust:latest
    stage: test
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
        - rustup component add clippy
        - cargo clippy
        - rustup default nightly
        - rustup component add rustfmt
        - cargo fmt -- --check

change-log:
    image: ubuntu:latest
    stage: test
    variables:
        GIT_STRATEGY: clone
    before_script:
        - apt-get update && apt-get install git -y
        - git fetch
    script:
        - bash -c "! git diff --exit-code origin/master CHANGELOG.md"
    except:
        - master
        - tags

readme-generator:
    image: rust:latest
    stage: test
    before_script:
        - cargo install cargo-readme
    script:
        - cargo run --bin readme-generator
        - git diff --exit-code
    except:
        - tags

pages:
    image: rust:latest
    stage: pages
    script:
        - cargo doc --no-deps
        - mv target/doc public/doc
    artifacts:
        paths:
            - public
    only:
        - master
