stages:
    - test
    - pages

#cpu-test:
#    image: rust:latest
#    stage: test
#    variables:
#        GIT_SUBMODULE_STRATEGY: recursive
#        CARGO_HOME: $CI_PROJECT_DIR/cargo
#    before_script:
#        - cargo install cargo-make
#    script:
#        - cargo make ci-cpu-test
#    cache:
#        key: cpu-test
#        paths:
#          - cargo/
#
#gpu-test:
#    image: registry.ritc.jp/ricos/truck/truck/rust-vulkan:_no_branch
#    stage: test
#    variables:
#        GIT_SUBMODULE_STRATEGY: recursive
#    script:
#        - /root/.cargo/bin/rustup update
#        - /root/.cargo/bin/cargo make ci-gpu-test
#    tags:
#        - gpu
#    artifacts:
#        paths:
#            - images
#
#wasm-test:
#    image: registry.ritc.jp/ricos/truck/truck/rust-webtools:_no_branch
#    stage: test
#    variables:
#        GIT_SUBMODULE_STRATEGY: recursive
#    before_script:
#        - rustup target add wasm32-unknown-unknown
#        - rustup update stable
#    script:
#        - deno lint
#        - mkdir public
#        - cargo make wasm-test
#        - mv truck-js/pkg public/adhoc-viewer
#        - mv dist public/webgpu-examples
#    artifacts:
#        paths:
#            - public
#
#lint-check:
#    image: rust:latest
#    stage: test
#    variables:
#        GIT_SUBMODULE_STRATEGY: recursive
#    script:
#        - rustup component add clippy
#        - cargo clippy
#        - rustup default nightly
#        - rustup component add rustfmt
#        - cargo fmt -- --check

change-log:
    image: debian:latest
    stage: test
    variables:
        GIT_STRATEGY: clone
    before_script:
        - apt-get update && apt-get install git -y
    script:
        - bash -c "! git diff --exit-code origin/master CHANGELOG.md"
    except:
        - master

#readme-generator:
#    image: rust:latest
#    stage: test
#    before_script:
#        - cargo install cargo-readme
#    script:
#        - cargo run --bin readme-generator
#        - git diff --exit-code

pages:
    image: rust:latest
    stage: pages
    script:
        - cargo doc --no-deps
        - mv target/doc public/doc
    artifacts:
        paths:
            - public
    only:
        - master
