stages:
    - test
    - pages

test:
    image: registry.ritc.jp/ricos/truck/truck/rust-vulkan:_no_branch
    stage: test
    script:
        - /root/.cargo/bin/cargo test
        - mkdir images
        - mv truck-platform/output images/platform
        - mv truck-rendimpl/output images/rendimpl
    except:
        - master
    tags:
        - gpu
    artifacts:
        paths:
            - images

pages:
    image: registry.ritc.jp/ricos/truck/truck/rust-vulkan:_no_branch
    stage: pages
    script:
        - /root/.cargo/bin/cargo clean
        - /root/.cargo/bin/cargo test
        - /root/.cargo/bin/cargo doc --no-deps
        - cp -r target/doc public
    artifacts:
        paths:
            - public
    tags:
        - gpu
    only:
        - master
