stages:
    - wgputest
    - test
    - pages

wgputest:
    image: registry.ritc.jp/ricos/truck/truck/rust-vulkan:_no_branch
    stage: test
    script:
        - git clone git@github.com:gfx-rs/wgpu-rs.git
        - git checkout v0.8
        - /root/.cargo/bin/cargo run --example capture
    except:
        - master
    tags:
        - gpu

test:
    image: registry.ritc.jp/ricos/truck/truck/rust-vulkan:_no_branch
    stage: test
    script:
        - /root/.cargo/bin/cargo test -- --nocapture
        - mkdir images
        - mv truck-platform/output images/platform
        - mv truck-rendimpl/output images/rendimpl
    except:
        - master
    tags:
        - gpu
    artifacts:
        paths:
            - images

pages:
    image: registry.ritc.jp/ricos/truck/truck/rust-vulkan:_no_branch
    stage: pages
    script:
        - /root/.cargo/bin/cargo clean
        - /root/.cargo/bin/cargo test -- --nocapture
        - /root/.cargo/bin/cargo doc --no-deps
        - cp -r target/doc public
    artifacts:
        paths:
            - public
    tags:
        - gpu
    only:
        - master
