stages:
    - test
    - pages

test:
    image: rust:latest
    stage: test
    script:
        - cargo test

pages:
    image: rust:latest
    stage: pages
    script:
        - cargo doc --no-deps
        - mv target/doc public
    artifacts:
        paths:
            - public
    only:
        - master