stages:
    - test
    - pages

test:
    image: rust:latest
    stage: test
    before_script:
        - apt-get update -y
        - apt-get install cmake -y
    script:
        - cargo test
    except:
        - master

pages:
    image: rust:latest
    stage: pages
    before_script:
        - apt-get update -y
        - apt-get install cmake -y
    script:
        - cargo clean
        - cargo test
        - cargo doc --no-deps
        - cp -r target/doc public
    artifacts:
        paths:
            - public
    only:
        - master