[workspace]
members = [
	"truck-base",
	"truck-geotrait",
	"truck-geometry",
	"truck-modeling",
	"truck-platform",
	"truck-polymesh",
	"truck-rendimpl",
	"truck-topology",
	"readme-generator",
	"glsl_utility",
]
