[package]
name = "truck-shapeops"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.16"
rand = "0.8.4"
rustc-hash = "1.1.0"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.24"
truck-base = { version = "0.1.1", path = "../truck-base" }
truck-geometry = { version = "0.1.1", path = "../truck-geometry" }
truck-topology = { version = "0.2.0", path = "../truck-topology" }
truck-meshalgo = { version = "0.1.0", path = "../truck-meshalgo" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.3", features = ["js"] }

[dev-dependencies]
serde_json = "1.0.68"
truck-modeling = { version = "0.2.1", path = "../truck-modeling" }
