[package]
name = "truck-shapeops"
version = "0.3.0"
edition = "2021"
description = "Provides boolean operations to Solid"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

[dependencies]
derive_more = "0.99.17"
rustc-hash = "1.1.0"
truck-base = { version = "0.4.0", path = "../truck-base" }
truck-geometry = { version = "0.4.0", path = "../truck-geometry" }
truck-topology = { version = "0.5.0", path = "../truck-topology" }
truck-meshalgo = { version = "0.3.0", path = "../truck-meshalgo" }

truck-geotrait = { version = "0.3.0", path = "../truck-geotrait" }

[dev-dependencies]
rand = "0.8.5"
serde_json = "1.0.108"
truck-modeling = { version = "0.5.0", path = "../truck-modeling" }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
getrandom = { version = "0.2.11", features = ["js"] }
