[package]
name = "truck-shapeops"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
truck-modeling = { version = "0.2.1", path = "../truck-modeling" }
truck-meshalgo = { version = "0.1.0", path = "../truck-meshalgo" }
