[package]
name = "truck-shapeops"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.123", features = ["derive"] }
rand = "0.8.3"
thiserror = "1.0.24"
truck-base = { version = "0.1.1", path = "../truck-base" }
truck-topology = { version = "0.2.0", path = "../truck-topology" }
truck-meshalgo = { version = "0.1.0", path = "../truck-meshalgo" }

[dev-dependencies]
rand = "0.8.3"
truck-geometry = { version = "0.1.1", path = "../truck-geometry" }
truck-modeling = { version = "0.2.1", path = "../truck-modeling" }
