[package]
name = "truck-polymesh"
version = "0.1.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"
exclude = ["tests/**/*.obj"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.17.0"
obj = "0.10.2"
truck-base = {path = "../truck-base"}
truck-topology = {path = "../truck-topology"}

[dev-dependencies]
