[package]
name = "truck-polymesh"
version = "0.1.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"
description = "defines polygon data structure and some algorithms handling mesh, including meshing the shapes"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]
exclude = ["tests/**/*.obj"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = { version = "0.17.0", features = ["serde"] }
obj = "0.10.2"
truck-base = { version = "0.1.0", path = "../truck-base" }
truck-topology = { version = "0.1.0", path = "../truck-topology" }
serde = { version = "*", features = ["derive"] }

[dev-dependencies]
