[package]
name = "truck-polymesh"
version = "0.3.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "defines polygon data structure and some algorithms handling mesh, including meshing the shapes"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]
exclude = ["examples/**/*.obj"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.7.2", features = ["derive"] }
rustc-hash = "1.1.0"
serde = { version = "1.0.130", features = ["derive"] }
truck-base = { version = "0.2.0", path = "../truck-base" }
truck-geotrait = { version = "0.1.0", path = "../truck-geotrait" }
thiserror = "1.0.29"
