[package]
name = "truck-rendimpl"
version = "0.1.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"
description = "visualization of shape and polygon mesh based on platform"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache License 2.0"
license-file = "../LICENSE"

keywords = ["truck", "graphics"]
categories = ["graphics"]

build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
bytemuck = { version = "1.4.1", features = ["derive"] }
truck-platform = { version = "0.1.0", path = "../truck-platform" }
truck-modeling = { version = "0.1.0", path = "../truck-modeling" }
truck-polymesh = { version = "0.1.0", path = "../truck-polymesh" }

[build-dependencies]
glsl-to-spirv = "0.1.7"

[dev-dependencies]
winit = "0.24.0"
glsl-to-spirv = "0.1.7"
stringreader = "0.1.1"
futures = "0.3.8"
