[package]
name = "truck-rendimpl"
version = "0.2.1"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"
description = "visualization of shape and polygon mesh based on platform"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]
exclude = ["*.png"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
bytemuck = { version = "1.7.2", features = ["derive"] }
truck-base = { version = "0.1.1", path = "../truck-base" }
truck-polymesh = { version = "0.2.1", path = "../truck-polymesh" }
truck-platform = { version = "0.2.1", path = "../truck-platform" }

[dev-dependencies]
env_logger = "0.9.0"
futures = "0.3.16"
rayon = "1.5.1"
serde_json = "1.0.66"
winit = "0.25.0"
truck-modeling = { version = "0.2.1", path = "../truck-modeling" }
truck-meshalgo = { version = "0.1.0", path = "../truck-meshalgo" }
