[package]
name = "truck-rendimpl"
version = "0.2.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"
description = "visualization of shape and polygon mesh based on platform"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]
exclude = ["*.png"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
bytemuck = { version = "1.4.1", features = ["derive"] }
truck-platform = { version = "0.2.0", path = "../truck-platform" }
truck-modeling = { version = "0.1.4", path = "../truck-modeling" }
truck-polymesh = { version = "0.2.0", path = "../truck-polymesh" }

[dev-dependencies]
winit = "0.24.0"
glsl-to-spirv = "0.1.7"
futures = "0.3.8"
