[package]
name = "truck-rendimpl"
version = "0.3.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "visualization of shape and polygon mesh based on platform"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]
exclude = ["*.png"]

[features]
default = []
webgl = ["truck-platform/webgl"]

[dependencies]
bytemuck = { version = "1.7.2", features = ["derive"] }
image = "0.23.14"
rustc-hash = "1.1.0"
truck-base = { version = "0.2.0", path = "../truck-base" }
truck-polymesh = { version = "0.3.0", path = "../truck-polymesh" }
truck-platform = { version = "0.3.0", path = "../truck-platform" }

[dev-dependencies]
env_logger = "0.9.0"
pollster = "0.2.4"
rayon = "1.5.1"
serde_json = "1.0.68"
truck-modeling = { version = "0.3.0", path = "../truck-modeling" }
truck-meshalgo = { version = "0.1.0", path = "../truck-meshalgo" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
instant = { version = "0.1.11", features = [ "now" ] }
winit = "0.25.0"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
instant = { version = "0.1.11", features = [ "now", "wasm-bindgen" ] }
winit = { version = "0.25.0", features = ["web-sys"] }
wasm-bindgen-futures = "0.4.28"
console_error_panic_hook = "0.1.6"
console_log = "0.1.2"
web-sys = { version = "0.3.53", features = ["Location"] }
