[package]
name = "truck-rendimpl"
version = "0.4.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "visualization of shape and polygon mesh based on platform"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]
exclude = ["*.png"]

[features]
default = []
webgl = ["truck-platform/webgl"]

[dependencies]
bytemuck = { version = "1.10.0", features = ["derive"] }
image = "0.24.2"
rustc-hash = "1.1.0"
truck-base = { version = "0.3.0", path = "../truck-base" }
truck-polymesh = { version = "0.4.0", path = "../truck-polymesh" }
truck-platform = { version = "0.4.0", path = "../truck-platform" }

[dev-dependencies]
async-trait = "0.1.56"
env_logger = "0.9.0"
pollster = "0.2.5"
rayon = "1.5.3"
serde_json = "1.0.82"
truck-modeling = { version = "0.4.0", path = "../truck-modeling" }
truck-meshalgo = { version = "0.2.0", path = "../truck-meshalgo" }
winit = "0.26.1"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
instant = { version = "0.1.12", features = [ "now" ] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
instant = { version = "0.1.12", features = [ "now", "wasm-bindgen" ] }
wasm-bindgen-futures = "0.4.31"
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
web-sys = { version = "0.3.57", features = ["Location"] }
