[package]
name = "truck-rendimpl"
version = "0.1.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
truck-platform = { path = "../truck-platform" }
truck-modeling = { path = "../truck-modeling" }
truck-polymesh = { path = "../truck-polymesh" }

[build-dependencies]
glsl-to-spirv = "*"

[dev-dependencies]
futures = "*"
