[package]
name = "truck-rendimpl"
version = "0.1.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
bytemuck = { version = "1.4.1", features = ["derive"] }
truck-platform = { path = "../truck-platform" }
truck-modeling = { path = "../truck-modeling" }
truck-polymesh = { path = "../truck-polymesh" }

[build-dependencies]
glsl-to-spirv = "0.1.7"

[dev-dependencies]
winit = "0.24.0"
glsl-to-spirv = "0.1.7"
stringreader = "0.1.1"
futures = "0.3.8"
