[package]
name = "truck_featwgpu"
version = "0.1.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "*"
cgmath = "*"
futures = "*"
image = "*"
truck_polymesh = {path = "../truck_polymesh"}
truck_modeling = {path = "../truck_modeling"}
truck_integral = {path = "../truck_integral"}
wgpu = "*"

[build-dependencies]
glsl-to-spirv = "*"

[dev-dependencies]
winit = "*"
stringreader = "*"
truck_io = {path = "../truck_io"}
