[package]
name = "truck_featwgpu"
version = "0.1.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "*"
bytemuck = "*"
cgmath = "*"
truck_polymesh = {path = "../truck_polymesh"}
truck_geometry = {path = "../truck_geometry"}
futures = "*"

[build-dependencies]
glsl-to-spirv = "*"

[dev-dependencies]
winit = "*"
wgpu-core = "*"
stringreader = "*"
truck_io = {path = "../truck_io"}
