[package]
name = "truck_topology"
version = "0.1.0"
authors = ["ytanimura <tanimura@ricos.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.2.0"

[dev-dependencies]
truck_geometry = {path = "../truck_geometry"}
# truck_io = {path = "../truck_io"}