[package]
name = "truck_polymesh"
version = "0.1.0"
authors = ["ytanimura <tanimura-yoshinori577@g.ecc.u-tokyo.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
truck_geometry = {path = "../truck_geometry"}
truck_topology = {path = "../truck_topology"}

[dev-dependencies]
truck_io = {path = "../truck_io"}
