[package]
name = "truck-meshalgo"
version = "0.3.0"
edition = "2021"
description = "Mesh algorighms, include tessellations of the shape."
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
rustc-hash = "1.1.0"
spade = "2.0.0"
truck-base = { version = "0.4.0", path = "../truck-base" }
truck-polymesh = { version = "0.5.0", path = "../truck-polymesh" }
truck-geotrait = { version = "0.3.0", path = "../truck-geotrait" }
truck-topology = { version = "0.5.0", path = "../truck-topology" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rayon = "1.6.1"

[dev-dependencies]
rand = "0.8.5"
serde_json = "1.0.91"
truck-modeling = { version = "0.5.0", path = "../truck-modeling" }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
getrandom = { version = "0.2.8", features = ["js"] }
