[package]
name = "truck-meshalgo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
truck-polymesh = { version = "0.2.1", path = "../truck-polymesh" }
truck-geotrait = { version = "0.1.0", path = "../truck-geotrait" }
truck-topology = { version = "0.2.0", path = "../truck-topology" }
spade = "1.8.2"
rand = "0.8.3"

[dev-dependencies]
truck-platform = { version = "0.2.1", path = "../truck-platform" }
truck-rendimpl = { version = "0.2.1", path = "../truck-rendimpl" }
truck-geometry = { version = "0.1.1", path = "../truck-geometry" }
truck-modeling = { version = "0.2.1", path = "../truck-modeling" }
image = "0.23.13"
futures = "0.3.12"
serde_json = "1.0.62"
