[package]
name = "truck-meshalgo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
truck-polymesh = { version = "0.2.1", path = "../truck-polymesh" }
