[package]
name = "truck-platform"
version = "0.2.1"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"
description = "graphic utility library based on wgpu"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

[features]
default = []
webgl = ["wgpu/webgl"]

[dependencies]
bytemuck = { version = "1.7.2", features = ["derive"] }
futures = "0.3.17"
rustc-hash = "1.1.0"
truck-base = { version = "0.1.1", path = "../truck-base" }
wgpu = "0.11.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
instant = { version = "0.1.11", features = [ "now" ] }
winit = "0.25.0"
[target.'cfg(target_arch = "wasm32")'.dependencies]
instant = { version = "0.1.11", features = [ "now", "wasm-bindgen" ] }
winit = { version = "0.25.0", features = ["web-sys"] }

[dev-dependencies]
image = "0.23.14"
rayon = "1.5.1"
env_logger = "0.9.0"
naga = { version = "0.7.0", features = ["wgsl-in"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-futures = "0.4.28"
console_error_panic_hook = "0.1.6"
console_log = "0.1.2"
web-sys = { version = "0.3.53", features = ["Location"] }
