[package]
name = "truck-platform"
version = "0.2.1"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"
description = "graphic utility library based on wgpu"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.8.1"
bytemuck = { version = "1.5.1", features = ["derive"] }
truck-base = { version = "0.1.1", path = "../truck-base" }

[dev-dependencies]
winit = "0.24.0"
image = "0.23.13"
futures = "0.3.12"
glsl-to-spirv = "0.1.7"
rayon = "1.5.0"
