[package]
name = "truck-platform"
version = "0.2.1"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"
description = "graphic utility library based on wgpu"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.10.1"
bytemuck = { version = "1.7.2", features = ["derive"] }
truck-base = { version = "0.1.1", path = "../truck-base" }

[dev-dependencies]
winit = "0.25.0"
image = "0.23.14"
futures = "0.3.16"
rayon = "1.5.1"
env_logger = "0.9.0"

[dev-dependencies.naga]
version = "0.6"
features = ["wgsl-in"]
