[package]
name = "truck-platform"
version = "0.5.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "graphic utility library based on wgpu"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

[features]
default = []
webgl = ["wgpu/webgl"]
wgpu_trace = ["wgpu/trace"]

[dependencies]
bytemuck = { version = "1.14.3", features = ["derive"] }
derive_more = "0.99.17"
futures-intrusive = "0.5.0"
rustc-hash = "1.1.0"
truck-base = { version = "0.4.0", path = "../truck-base" }
wgpu = "0.19.1"
winit = "0.29.11"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
instant = { version = "0.1.12", features = [ "now" ] }
[target.'cfg(target_arch = "wasm32")'.dependencies]
instant = { version = "0.1.12", features = [ "now", "wasm-bindgen" ] }
web-sys = "=0.3.67"

[dev-dependencies]
image = "0.24.9"
rayon = "1.9.0"
env_logger = "0.11.2"
naga = { version = "0.19.0", features = ["wgsl-in"] }
pollster = "0.3.0"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-futures = "0.4.41"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
web-sys = { version = "=0.3.67", features = ["Location"] }
