[package]
name = "truck-platform"
version = "0.3.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "graphic utility library based on wgpu"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

[features]
default = []
webgl = ["wgpu/webgl"]
wgpu_trace = ["wgpu/trace"]

[dependencies]
bytemuck = { version = "1.7.2", features = ["derive"] }
derive_more = "0.99.17"
rustc-hash = "1.1.0"
truck-base = { version = "0.2.0", path = "../truck-base" }
wgpu = "0.12.0"
winit = "0.26.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
instant = { version = "0.1.12", features = [ "now" ] }
[target.'cfg(target_arch = "wasm32")'.dependencies]
instant = { version = "0.1.12", features = [ "now", "wasm-bindgen" ] }

[dev-dependencies]
image = "0.23.14"
rayon = "1.5.1"
env_logger = "0.9.0"
naga = { version = "0.7.2", features = ["wgsl-in"] }
pollster = "0.2.4"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-futures = "0.4.28"
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
web-sys = { version = "0.3.55", features = ["Location"] }
