[package]
name = "truck-js"
version = "0.1.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"
description = "Javascript wrapper for truck"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
console_error_panic_hook = { version = "0.1.6", optional = true }
derive_more = "0.99.16"
rustc-hash = "1.1.0"
truck-modeling = { version = "0.2.1", path = "../truck-modeling" }
truck-meshalgo = { version = "0.1.0", path = "../truck-meshalgo" }
wasm-bindgen = "0.2.78"
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.28"
