[package]
name = "truck_glrender"
version = "0.1.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.27.0"
cgmath = "*"
truck_geometry = {path = "../truck_geometry"}
truck_polymesh = {path = "../truck_polymesh"}

[dev-dependencies]
truck_io = {path = "../truck_io"}
