[package]
name = "truck_io"
version = "0.1.0"
authors = ["ytanimura <tanimura@ricos.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obj = "0.9.1"
truck_geometry = {path = "../truck_geometry"}
truck_topology = {path = "../truck_topology"}
truck_polymesh = {path = "../truck_polymesh"}
serde = "1.0.106"
serde_derive = "1.0.106"
serde_json = "1.0.51"
