[package]
name = "truck-stepio"
version = "0.1.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "Reads/writes STEP files from/to truck"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

[features]
default = []
from_other_crate = []

[dependencies]
chrono = { version = "0.4.19", features = ["wasmbind"] }
truck-base = { version = "0.3.0", path = "../truck-base" }
truck-geotrait = { version = "0.2.0", path = "../truck-geotrait" }
truck-geometry = { version = "0.3.0", path = "../truck-geometry" }
truck-polymesh = { version = "0.4.0", path = "../truck-polymesh" }
truck-topology = { version = "0.4.0", path = "../truck-topology" }
truck-modeling = { version = "0.4.0", path = "../truck-modeling" }

[dev-dependencies]
derive-new = "0.5.9"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
itertools = "0.10.3"
nom = "7.1.1"
ruststep = "0.2.0"
ruststep-derive = "0.2.0"
espr-derive = "0.2.0"
