[package]
name = "truck-stepio"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = { version = "0.4.19", features = ["wasmbind"] }
truck-base = { version = "0.3.0", path = "../truck-base" }
truck-geotrait = { version = "0.2.0", path = "../truck-geotrait" }
truck-geometry = { version = "0.3.0", path = "../truck-geometry" }
truck-polymesh = { version = "0.4.0", path = "../truck-polymesh" }
truck-topology = { version = "0.4.0", path = "../truck-topology" }
truck-modeling = { version = "0.4.0", path = "../truck-modeling" }

[dev-dependencies]
derive-new = "0.5.9"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
itertools = "0.10.3"
nom = "7.1.1"
ruststep = "0.2.0"
ruststep-derive = "0.2.0"
espr-derive = "0.2.0"
