[package]
name = "truck-stepio"
version = "0.2.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "Reads/writes STEP files from/to truck"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

[dependencies]
derive_more = "0.99.17"
chrono = { version = "0.4.23", features = ["wasmbind"] }
rustc-hash = "1.1.0"
ruststep = { git = "https://github.com/ricosjp/ruststep.git" }
ruststep-derive = { git = "https://github.com/ricosjp/ruststep.git" }
serde = { version = "1.0.151", features = ["derive"] }
truck-base = { version = "0.4.0", path = "../truck-base" }
truck-geotrait = { version = "0.3.0", path = "../truck-geotrait" }
truck-geometry = { version = "0.4.0", path = "../truck-geometry" }
truck-polymesh = { version = "0.5.0", path = "../truck-polymesh" }
truck-topology = { version = "0.5.0", path = "../truck-topology" }
truck-modeling = { version = "0.5.0", path = "../truck-modeling" }

[dev-dependencies]
derive-new = "0.5.9"
serde_json = "1.0.91"
itertools = "0.10.5"
nom = "7.1.1"
espr-derive = "0.3.0"
truck-meshalgo = { version = "0.3.0", path = "../truck-meshalgo" }
