[package]
name = "truck-stepio"
version = "0.1.0"
edition = "2018"
# build = "build.rs"

# [build-dependencies]
# espr = "0.1.0"
# quote = "1.0.9"

[dependencies]
truck-base = { version = "0.2.0", path = "../truck-base" }
truck-geotrait = { version = "0.1.0", path = "../truck-geotrait" }
truck-geometry = { version = "0.2.0", path = "../truck-geometry" }
truck-polymesh = { version = "0.3.0", path = "../truck-polymesh" }
truck-topology = { version = "0.3.0", path = "../truck-topology" }

[dev-dependencies]
derive-new = "0.5.9"
serde = { version = "1.0.131", features = ["derive"] }
itertools = "0.10.1"
nom = "7.0.0"
ruststep = { git = "https://github.com/ricosjp/ruststep.git", branch = "generate-holder-struct-for-type" }
ruststep-derive = { git = "https://github.com/ricosjp/ruststep.git", branch = "generate-holder-struct-for-type" }
espr-derive = { git = "https://github.com/ricosjp/ruststep.git", branch = "generate-holder-struct-for-type" }
